//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALS.Glance.Api.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ALS.Glance.Api.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad Request.
        /// </summary>
        internal static string BadRequestErrorMessage {
            get {
                return ResourceManager.GetString("BadRequestErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application not found.
        /// </summary>
        internal static string Conflict_Authorizations_ApiApplicationNotFoundScoped {
            get {
                return ResourceManager.GetString("Conflict_Authorizations_ApiApplicationNotFoundScoped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        internal static string Conflict_Authorizations_ApiUserNotFound {
            get {
                return ResourceManager.GetString("Conflict_Authorizations_ApiUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password.
        /// </summary>
        internal static string Conflict_Authorizations_IncorrectPassword {
            get {
                return ResourceManager.GetString("Conflict_Authorizations_IncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Credentials.
        /// </summary>
        internal static string Conflict_Authorizations_InvalidCredentials {
            get {
                return ResourceManager.GetString("Conflict_Authorizations_InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email must be confirmed.
        /// </summary>
        internal static string Conflict_Authorizations_MissingEmailConfirmation {
            get {
                return ResourceManager.GetString("Conflict_Authorizations_MissingEmailConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh token not found.
        /// </summary>
        internal static string Conflict_Authorizations_RefreshTokenNotFound {
            get {
                return ResourceManager.GetString("Conflict_Authorizations_RefreshTokenNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request is in conflict with server information.
        /// </summary>
        internal static string Conflict_Shared_GenericMessage {
            get {
                return ResourceManager.GetString("Conflict_Shared_GenericMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already in use.
        /// </summary>
        internal static string Conflict_Users_DuplicatedEmailScoped {
            get {
                return ResourceManager.GetString("Conflict_Users_DuplicatedEmailScoped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password.
        /// </summary>
        internal static string Conflict_Users_IncorrectOldPassword {
            get {
                return ResourceManager.GetString("Conflict_Users_IncorrectOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Bem vindo,&lt;/p&gt;
        ///&lt;p&gt;Obrigado por criar a sua conta na &lt;b&gt;Aplicação Móvel Farmácias Portuguesas.&lt;/b&gt;&lt;/p&gt;
        ///&lt;p&gt;Para validar o registo na aplicação, visite o seguinte &lt;a href=&quot;{0}&quot;&gt;link&lt;/a&gt;.&lt;/p&gt;
        ///&lt;p&gt;Se não solicitou uma criação de conta na Aplicação Móvel Farmácias Portuguesas, por favor, ignore esta mensagem.&lt;/p&gt;
        ///Os melhores cumprimentos,&lt;br/&gt;
        ///Farmácias Portuguesas.
        /// </summary>
        internal static string EmailBodyConfirmation {
            get {
                return ResourceManager.GetString("EmailBodyConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Caro utilizador,&lt;/p&gt;
        ///&lt;p&gt;Este e-mail foi enviado automaticamente, em resposta ao seu pedido de recuperação de palavra-chave na &lt;b&gt;Aplicação ALS Glance.&lt;/b&gt;&lt;/p&gt;
        ///&lt;p&gt;Este procedimento é efetuado para sua segurança, sendo que apenas você, o destinatário deste e-mail, poderá efetuar o próximo passo no processo de recuperação de palavra-chave.&lt;/p&gt;
        ///&lt;p&gt;Para recuperar a sua palavra-chave e assim aceder à sua conta, visite o seguinte &lt;a href=&quot;{0}&quot;&gt;link&lt;/a&gt;.&lt;/p&gt;
        ///&lt;p&gt;Se não solicitou a recuperação de palavra-chave na  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmailBodyPasswordResetConfirmation {
            get {
                return ResourceManager.GetString("EmailBodyPasswordResetConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALS Glance – Criação de Conta.
        /// </summary>
        internal static string EmailSubjectConfirmation {
            get {
                return ResourceManager.GetString("EmailSubjectConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALS Glance – Recuperação de Palavra-chave.
        /// </summary>
        internal static string EmailSubjectPasswordResetConfirmation {
            get {
                return ResourceManager.GetString("EmailSubjectPasswordResetConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credentials can not be null or empty.
        /// </summary>
        internal static string EmptyCredentialsErrorMessage {
            get {
                return ResourceManager.GetString("EmptyCredentialsErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        internal static string ModelValidation_RequiredScoped {
            get {
                return ResourceManager.GetString("ModelValidation_RequiredScoped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Implemented.
        /// </summary>
        internal static string NotImplementedErrorMessage {
            get {
                return ResourceManager.GetString("NotImplementedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The authorization has expired. Please refresh your access..
        /// </summary>
        internal static string TokenExpiredErrorMessage {
            get {
                return ResourceManager.GetString("TokenExpiredErrorMessage", resourceCulture);
            }
        }
    }
}
